In [4]:
import numpy as np

objects = np.array([[3,2,2],[4,3,2],[4,7,5]])

print(objects)
print(objects.shape)
print(objects.ndim)
print("Haw kaw",objects[1,2])
print("2nd object is:\n ","First element: ", objects[1,0],"\n  Second element:",objects[1,1],"\n  Third element: ",objects[1,2])
sobzero = np.zeros([2,2])
print(sobzero)
sliceob =objects[0:,:2]
print(sliceob)

[[3 2 2]
 [4 3 2]
 [4 7 5]]
(3, 3)
2
Haw kaw 2
2nd object is:
  First element:  4 
  Second element: 3 
  Third element:  2
[[0. 0.]
 [0. 0.]]
[[3 2]
 [4 3]
 [4 7]]


# slicing array objects numpy

In [19]:
sliceob =objects[0:,:2]
print(sliceob)

[[  3   2]
 [400   3]
 [  4   7]]


In [18]:
objects[1,0] = 400
print(objects)

[[  3   2   2]
 [400   3   2]
 [  4   7   5]]


In [32]:
sliceob = objects[0:,:2]
print(sliceob)

[[  3   2]
 [400   3]
 [  4   7]]


# Slicing and assigning values to sliceed object, reference copy using(original copy not changed)


In [29]:
sliceob = np.array(objects[0:,:2])
sliceob[1,0] = 40
print(sliceob)
print(objects)


[[ 3  2]
 [40  3]
 [ 4  7]]
[[  3   2   2]
 [400   3   2]
 [  4   7   5]]


# filtering with condition and printing

In [33]:
filter = (objects > 2) 
filter

array([[ True, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [72]:
print(objects[filter])

[  3 400   3   4   7   5]


In [5]:
objects[(objects > 2)& (objects < 2)]
print(objects)


[[3 2 2]
 [4 3 2]
 [4 7 5]]


# data type of array

In [6]:
print(objects)

[[3 2 2]
 [4 3 2]
 [4 7 5]]


In [7]:
for i in objects:
    print(i)

[3 2 2]
[4 3 2]
[4 7 5]


In [8]:
print(objects.dtype)

int32


In [13]:
tcf1= np.array([[2.4,6.8,7.54],[3.4,2.4,3.5]],dtype=int)
tcf2= np.array([[4.4,3.8,2.5],[3.3,5.4,4.5]])

print(tcf1.dtype)
print(tcf2.dtype)
print(tcf1)




int32
float64
[[2 6 7]
 [3 2 3]]


# numpy statistical operations\random,mean,

In [26]:
#using random function
arr = 10* np.random.randn(2,5)


print(arr)
#print(arr.shape)

[[-18.89000348   1.93855212 -19.99041634   7.33280606   5.44659658]
 [-10.43741689  -3.66546095  -7.21117998  16.54036245 -13.14224203]]


In [27]:
print(arr.mean())

-4.2078402463668025


In [28]:
#for rows 
print(arr.mean(axis = 1))

[-4.83249301 -3.58318748]


In [29]:
#for columns
print(arr.mean(axis = 0))

[-14.66371019  -0.86345442 -13.60079816  11.93658425  -3.84782272]


In [33]:
ss1 = arr.sum(axis = 1)
print(ss)
ss2 = arr.sum(axis = 0)
print(ss2)

[-24.16246507 -17.9159374 ]
[-29.32742038  -1.72690883 -27.20159631  23.87316851  -7.69564545]


In [35]:
medians = np.median(arr, axis = 0)
print(medians)

[-14.66371019  -0.86345442 -13.60079816  11.93658425  -3.84782272]


# sorting

In [42]:
unsorted = np.random.randn(10)
print(unsorted)

[ 1.24281833  0.87072901  1.00892802  1.04018237  0.42710797 -0.20605598
  0.02537983 -1.16942608 -0.36490916  0.0562972 ]


In [41]:
#unsorted.sort()
#print(unsorted)

In [44]:
sorted = np.array(unsorted)
sorted.sort()
print(sorted)

[-1.16942608 -0.36490916 -0.20605598  0.02537983  0.0562972   0.42710797
  0.87072901  1.00892802  1.04018237  1.24281833]


# uniqe element finding 

In [45]:
baray = np.array([2,3,1,6,3,7,3,8,9,4,5,6,3,2,4,6,7,8,9,6,4,3,7])
print(np.unique(baray))

[1 2 3 4 5 6 7 8 9]


# set operations 

In [58]:
wash_sale = np.array(["toyota","audi","sadi","porche","mitsubishi"])
newy_sale = np.array(["porche","audi","goyota","fazero","proton"])

cms = np.intersect1d(wash_sale,newy_sale)
#print(cms)
for car in cms:
    print (car)

print("\n")

print("All sales:")
alls = np.union1d(wash_sale,newy_sale)
#print(alls)
for car in alls:
    print(car)
    
print("\n")    
uncs = np.setdiff1d(wash_sale,newy_sale)
for car in uncs:
    print(car)


#checks if washionton car sale is sold in newyork
differ = np.in1d(wash_sale,newy_sale)
print(differ)


audi
porche


All sales:
audi
fazero
goyota
mitsubishi
porche
proton
sadi
toyota


mitsubishi
sadi
toyota
[False  True False  True False]
